apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: nginx-ingress
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  ports:
  - name: metrics
    port: 10254
    protocol: TCP
    targetPort: metrics
  selector:
    k8s-app: nginx-ingress
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: nginx-ingress
  name: nginx-ingress-monitor
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    port: metrics
  namespaceSelector:
    matchNames:
    - ingress-nginx
  selector:
    matchLabels:
      k8s-app: nginx-ingress
